### PR TITLE
Implement CI/Release flow similar to base package

### PR DESCRIPTION
**Pull request by mattletw**
This Pull request replaces current CI flow and implements a similar like flow as the base package (Automapper repo).

This enables to push the tagged versions towards NuGet.

The NUGET_API_KEY secret needs to be set with the right API key for NuGet.

Solves: https://github.com/AutoMapper/AutoMapper.EF6/issues/30

### CODE REVIEW

**Comment by lbargaoanu** [comment]
@jbogard [Help!](https://github.com/AutoMapper/AutoMapper.EF6/runs/3085499734?check_suite_focus=true#step:5:11) :)

**Comment by mattletw** [comment]
@lbargaoanu @jbogard any help needed from my side? the image posted in https://github.com/AutoMapper/AutoMapper.EF6/pull/29 would give me the impression that the API KEY is set but doesn't have the right permissions to update the AutoMapper.EF6 package.

**Comment by lbargaoanu** [comment]
Yes, we need @jbogard :)

**Comment by mattletw** [comment]
@lbargaoanu @jbogard Do we have any update on this one already? 😄

**Comment by lbargaoanu** [comment]
https://www.nuget.org/packages/AutoMapper.EF6/

**Comment by mattletw** [comment]
@lbargaoanu @jbogard awesome guys 🙌 🙌 🙌 

Thanks a lot!

**Pull request merged**
