### PR TITLE
CI Implementation for the project

### LINKED ISSUE #27: Nuget package targets outdated
Hi, the nuget package is outdated and targets .NETFramework 4.6.1 but not .NETStandard, can you please update the nuget package?

Thanks

### PR DESCRIPTION
**Pull request by mudassir014**
Fix #27 

-Added CI for Automapper.EF6
-Secrets needed to be added to run this CI
  1. MYGET_CI_NURL ~ Nuget server URL
  2. MYGET_CI_API_KEY ~ Nuget server key

Testing:
-Tested by publishing on personal NuGet server and then reference it in test app targetting .net core 3.1.

### CODE REVIEW

**Comment by lbargaoanu** [comment]
@jbogard We need the settings in the repo.

**Comment by lbargaoanu** [comment]
@mudassir014 The MyGet url is https://www.myget.org/F/automapperdev/api/v3/index.json. We don't need a setting for that one.

**Comment by jbogard** [comment]
The settings are already in the org:
image

**Comment by lbargaoanu** [comment]
https://myget.org/feed/automapperdev/package/nuget/AutoMapper.EF6
@mudassir014 Thanks!

**Comment by mudassir014** [comment]
@lbargaoanu 
Thank you for letting me contribute. This is my first contribution and also to a well known repo. Can't express my happiness :)

**Pull request merged**
